//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Enums
{
		public enum MouseButton {Left,Right,Wheel,NONE};
		public enum MouseState {Up,Down,NONE};
        public enum GraphElementType {Node,Edge};
        public enum DFGProcess {Import,Export};
        public enum SL_State{SAVE,LOAD};
        public enum LayoutMode {Big,Small};
}

